### ISSUE TITLE
User Auth MVP 

### ISSUE THREAD

**Issue by AdamYLiang** [joeqnicholson/grimeo#1]
Good work! I like the theme, here are some changes:

**Functionality** 
- [x] Signup seems to give a 422 error 
- [x] Login user shouldn't ask to input `First name` 
- [x] Font error in console, seems to have to do with how the font is being imported 
- [x] Add splash page (ex. `Grimeo can help`) and buttons to `Join for free`. The `See Plans` button can be a demo user button. 
- [x] Sign up form should be a separate page/component instead of a modal. 

**CSS** 
- [x] Login and watch in the nav bar seem to not be aligned.
- [x] `Join` button should be slightly longer to match original app.
- [x] Modal closeout button (`X`) and placeholder text should be slightly bigger to match original app. 
- [x] Consider making the DemoUser a different color to match the OAuth on original app. 

Let me know if you have any questions about these changes!

**Comment by joeqnicholson** [comment]
Hey Adam other than the font problem these have been addressed

**Comment by joeqnicholson** [comment]
went with another font, all done over here

**Comment by AdamYLiang** [comment]
Looks great, nice work!
